import type {Resource} from '../types';
import { validateResource } from '../lib/catalog-schema.mjs';
type Edited=Resource & {revision?:number};
const status=document.querySelector('#admin-status')!;
const form=document.querySelector<HTMLFormElement>('#resource-form')!;
const picker=document.querySelector<HTMLSelectElement>('#resource-picker')!;
const arrays=['levels','skills','tags','exams','formats','languages'];
let selected:Edited|null=null; let entries:Edited[]=[]; let imported:Edited[]=[];
async function reload(){const response=await fetch('/api/admin/resources');if(!response.ok)throw Error('管理员验证未通过。请先在 Cloudflare Access 完成登录；尚未配置的站点会拒绝目录写入。');entries=((await response.json()) as {resources:Edited[]}).resources;picker.replaceChildren(new Option('选择资源',''));entries.forEach(r=>picker.add(new Option(`${r.titleZh} · ${r.status}`,r.id)));}
function edit(r:Edited|null){selected=r;form.reset();for(const c of Array.from(form.elements))if(c instanceof HTMLInputElement||c instanceof HTMLSelectElement||c instanceof HTMLTextAreaElement){const v=r?.[c.name as keyof Edited];c.value=arrays.includes(c.name)?(v as string[]??[]).join(','):String(v??c.value);}const id=form.elements.namedItem('id') as HTMLInputElement;id.readOnly=!!r;}
async function save(r:Edited){const response=await fetch('/api/admin/resources',{method:r.revision?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(r)});if(!response.ok){const error=await response.json() as {message?:string};throw Error(response.status===409?'版本冲突或 ID、路径、链接重复。请重新读取后编辑。':error.message??'保存失败');}return response.json();}
picker.addEventListener('change',()=>edit(entries.find(r=>r.id===picker.value)??null));
document.querySelector('#new-resource')?.addEventListener('click',()=>edit(null));
form.addEventListener('submit',async event=>{event.preventDefault();try{const data:Record<string,unknown>=Object.fromEntries(new FormData(form));for(const k of arrays)data[k]=String(data[k]).split(/[,，]/).map(v=>v.trim()).filter(Boolean);data.canonicalUrl=data.url;data.rights=selected?.rights??'link-only';const r=validateResource(data) as Edited;if(selected)r.revision=selected.revision;await save(r);await reload();edit(entries.find(v=>v.id===r.id)??null);status.textContent='保存成功。';}catch(error){status.textContent=String(error);}});
document.querySelector('#export-catalog')?.addEventListener('click',async()=>{try{const response=await fetch('/api/admin/export');if(!response.ok)throw Error('导出失败');const url=URL.createObjectURL(new Blob([JSON.stringify(await response.json(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='deutsch-public-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){status.textContent=String(error);}});
document.querySelector('#catalog-file')?.addEventListener('change',async event=>{const file=(event.target as HTMLInputElement).files?.[0];const saveButton=document.querySelector<HTMLButtonElement>('#save-import')!;saveButton.disabled=true;imported=[];try{if(!file||file.size>1024*1024)throw Error('文件为空或超过 1 MB');const data=JSON.parse(await file.text());const rows=Array.isArray(data)?data:data.resources;if(!Array.isArray(rows)||rows.length>200)throw Error('每次最多导入 200 条');imported=rows.map(r=>validateResource({...r,status:'draft'}));document.querySelector('#import-preview')!.textContent=imported.map(r=>`${r.titleZh} | ${r.primaryCategory} | ${r.url}`).join('\n');saveButton.disabled=false;}catch(error){status.textContent=String(error);}});
document.querySelector('#save-import')?.addEventListener('click',async()=>{let count=0;try{for(const r of imported){await save(r);count++;}await reload();status.textContent=`已保存 ${count} 条草稿。`;}catch(error){status.textContent=`已保存 ${count} 条，其余未导入：${error}`;}});
reload().then(()=>{document.querySelector<HTMLElement>('#admin-editor')!.hidden=false;status.textContent='管理员验证通过。';}).catch(error=>{status.textContent=String(error);});
