import type {Resource} from '../types';
import { buildResourceEdit, prepareDraftImport } from '../lib/catalog-edit.mjs';
type Edited=Resource & {revision?:number};
const status=document.querySelector('#admin-status')!;
const form=document.querySelector<HTMLFormElement>('#resource-form')!;
const picker=document.querySelector<HTMLSelectElement>('#resource-picker')!;
const arrays=['levels','skills','tags','exams','formats','mediaTypes','languages','interfaceLanguages','aliases'];
let selected:Edited|null=null; let entries:Edited[]=[]; let imported:Edited[]=[];
async function reload(){const response=await fetch('/api/admin/resources');if(!response.ok)throw Error('管理员验证未通过。请先在 Cloudflare Access 完成登录；尚未配置的站点会拒绝目录写入。');entries=((await response.json()) as {resources:Edited[]}).resources;picker.replaceChildren(new Option('选择资源',''));entries.forEach(r=>picker.add(new Option(`${r.titleZh} · ${r.status}`,r.id)));}
function edit(r:Edited|null){selected=r;form.reset();for(const c of Array.from(form.elements))if(c instanceof HTMLInputElement||c instanceof HTMLSelectElement||c instanceof HTMLTextAreaElement){const v=r?.[c.name as keyof Edited];c.value=arrays.includes(c.name)?(v as string[]??[]).join(','):String(v??c.value);}const id=form.elements.namedItem('id') as HTMLInputElement;id.readOnly=!!r;}
async function save(r:Edited){const response=await fetch('/api/admin/resources',{method:r.revision?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(r)});if(!response.ok){const error=await response.json() as {message?:string};throw Error(response.status===409?'版本冲突或 ID、路径、链接重复。请重新读取后编辑。':error.message??'保存失败');}return response.json();}
picker.addEventListener('change',()=>edit(entries.find(r=>r.id===picker.value)??null));
document.querySelector('#new-resource')?.addEventListener('click',()=>edit(null));
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector<HTMLButtonElement>('[type=submit]')!;button.disabled=true;try{const r=buildResourceEdit(selected,new FormData(form)) as Edited;if(selected)r.revision=selected.revision;const result=await save(r) as {revision:number};edit({...r,revision:result.revision});status.textContent='保存成功。';await reload();}catch(error){status.textContent=String(error);}finally{button.disabled=false;}});
document.querySelector('#export-catalog')?.addEventListener('click',async()=>{try{const response=await fetch('/api/admin/export');if(!response.ok)throw Error('导出失败');const url=URL.createObjectURL(new Blob([JSON.stringify(await response.json(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='deutsch-public-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){status.textContent=String(error);}});
function importPreview(){document.querySelector('#import-preview')!.textContent=imported.map(r=>`${r.titleZh} | ${r.primaryCategory} | ${r.url}`).join('\n');}
document.querySelector('#catalog-file')?.addEventListener('change',async event=>{const file=(event.target as HTMLInputElement).files?.[0];const saveButton=document.querySelector<HTMLButtonElement>('#save-import')!;saveButton.disabled=true;imported=[];importPreview();try{if(!file||file.size>1024*1024)throw Error('文件为空或超过 1 MB');const data=JSON.parse(await file.text());const rows=Array.isArray(data)?data:data?.resources;if(!Array.isArray(rows))throw Error('资源文件格式不正确');await reload();imported=prepareDraftImport(rows,entries) as Edited[];importPreview();saveButton.disabled=false;status.textContent=`预览通过：${imported.length} 条新草稿。`;}catch(error){status.textContent=String(error);}});
document.querySelector<HTMLButtonElement>('#save-import')?.addEventListener('click',async event=>{const button=event.currentTarget as HTMLButtonElement;const fileInput=document.querySelector<HTMLInputElement>('#catalog-file')!;button.disabled=true;fileInput.disabled=true;let count=0;try{while(imported.length){await save(imported[0]);imported.shift();count++;importPreview();status.textContent=`已保存 ${count} 条，剩余 ${imported.length} 条。`;}await reload();status.textContent=`已保存 ${count} 条草稿。`;}catch(error){status.textContent=`已保存 ${count} 条，其余 ${imported.length} 条未导入：${error}`;}finally{button.disabled=!imported.length;fileInput.disabled=false;}});
reload().then(()=>{document.querySelector<HTMLElement>('#admin-editor')!.hidden=false;status.textContent='管理员验证通过。';}).catch(error=>{status.textContent=String(error);});
